version: '3.1'
services:
  # Servicio de Odoo
  odoo:
    image: odoo:17.0
    platform: linux/arm64  
    depends_on: 
      - db
    ports:
      - "8069:8069"         # Puerto principal de Odoo
    volumes:
      - odoo-data:/var/lib/odoo
      - ./addons:/mnt/extra-addons
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
      - DB_PORT=5432
    restart: always
  
  # Servicio de la base de datos PostgreSQL
  db: 
    image: postgres:15
    platform: linux/arm64
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  odoo-data:
  postgres_data: